apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-mcglzbky
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-mcglzbky:4c97d34db2ef1285dac7f58915dddac28e21575a@sha256:c0c0b9cb750107b1e4110cd3d2189026fd3669d5b1c4ef62008ff0987bd0be09
        name: container-image  
